export const SET_USER_STATE = "SET_USER_STATE";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SET_USER_PROJECT = "SET_USER_PROJECT";
export const SET_USER_C_PROJECT = "SET_USER_C_PROJECT";